### ISSUE TITLE
Repo goals

### ISSUE THREAD

**Issue by matted-zz** [gifford-lab/deepsea-predict-docker#1]
How is this different (or how will it be different) from the other repo, deepsea-docker?

**Comment by haoyangz** [comment]
This repo is for **predicting** with the published DeepSEA model trained on 919 epigenomics features, while the other [repo](https://github.com/gifford-lab/deepsea-docker) is for **re-training** a new DeepSEA model on customized data. It will close this [issue](https://github.com/gifford-lab/deepsea-docker/issues/1) for the other repo. A full README is to be uploaded.

**Comment by matted-zz** [comment]
Hm, it seems that I forgot the codebases were so separate.  What do you think about (eventually) combining this with the existing `deepsea-docker` repo, maybe separating their chunks into a `train` and `test` folder?  That way we would reduce some of the repetition between the two `Dockerfiles` and have a clearer entry point into the project (with appropriate updated documentation, etc.).
