### ISSUE TITLE
Cannot read absolute input path for fasta file

### ISSUE THREAD

**Issue by akmorrow13** [gifford-lab/deepsea-predict-docker#2]
When running the following command:
`docker run -v $(pwd)/output:/output --rm haoyangz/deepsea-predict-docker python rundeepsea.py $(pwd)/example.fasta /output`

Generates the following error:

```
cp: cannot stat '/Users/username/Desktop/fasta_files/example.fasta': No such file or directory
Finished creating output file. Now clean up...
Everything done.
Traceback (most recent call last):
  File "rundeepsea.py", line 19, in <module>
    check_call(['cp',infilename,tempdir+'/infile.fasta'])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cp', '/Users/username/Desktop/fasta_files/example.fasta', '/tmp/tmpfL0dlh/infile.fasta']' returned non-zero exit status 1
```

This does not happen when running the same command in python out of docker. Any ideas?

**Comment by haoyangz** [comment]
Try running the exact code in the example. 

The problem with what you've run is that your current path $(pwd) doesn't exist in the docker container. If you wish to predict on customized FASTA file, please follow the second example where you mount both the input and ouput to the docker container.

**Comment by akmorrow13** [comment]
`docker run -v $(pwd)/example.fasta:/infile  -v $(pwd)output:/output --rm haoyangz/deepsea-predict-docker python rundeepsea.py /infile /output`

Does not throw an error but does not print the normal output messages that are shown when running the example files provided in the docker container. The output files are not saved.

**Comment by akmorrow13** [comment]
`docker run -v $(pwd)/example.fasta:/infile  -v $(pwd)output:/output --rm haoyangz/deepsea-predict-docker python rundeepsea.py /infile /output`

Does not output any error message but does not print stdout as when running the example files provided in the docker container. The output files are not saved

**Comment by haoyangz** [comment]
Ok, so there are a few things that could have gone wrong:
- Make sure you have a `example.fasta` file in your current directory
- It should be `$(pwd)/output` rather than `$(pwd)output`
- Please change both `/infile` to `/infile.fasta`, as the original deepsea code will check if the input ends with .fasta . I will update this in the README soon.

**Comment by haoyangz** [comment]
I just updated the README and included an `example.fasta` in the repository. Please do `git pull` and and try again!

**Comment by akmorrow13** [comment]
This works, thanks!
